version: "3.8"

services:
  db-redis:
    container_name: redis_db_test_node
    image: redis:latest
    ports:
      - "6379:6379"

  web-api-express:
    container_name: prueba_node_redis
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/api
    command: sh -c "cd /api && npm install && npm start"
    depends_on:
      - db-redis